### PR TITLE
README / comments / Xcode / CHANGELOG / about panel updates

### LINKED ISSUE #5: Needs about
how else do I get twitter followers?

### PR DESCRIPTION
**Pull request by movesmyers**
Updated comments in the top of the files which were referencing a different project name. 
Updated README with a few (opinionated) grammatical changes. 
Updated build settings to silence Xcode warnings. 
Added about panel. Closes #5 
Removed the CHANGELOG.md, as it is for ARAnalytics, not Wallpapers

### CODE REVIEW

**Comment by orta** [comment]
Wow - awesome

**Comment by orta** [comment]
lets see if I can get this merged manually

**Comment by orta** [comment]
Thanks - got it 👍  awesome

**Comment by movesmyers** [comment]
Cool, thanks!

**Pull request merged**
